Integration tests (POC)
27medkamal/tmux-session-wizard pull request #15
Opened 2024-12-17 01:42 UTC by mandos

@27medkamal before implementing the duplicate session feature (#10) I would like to clean up code a bit (especially 't' binary) and introduce tests to verify the plugin's behavior real tmux and zoxide. 

This  commit introduces a proposal of integration test that are executed in Docker.

**Test Scenario**
Each integration test follows these steps:

- Stop tmux server if exists
- set up a tmux configuration in '/tmp/tmux.conf' with the plugin initialization
- Run the test (tmux session is detached)
- Clean up: remove zoxide and tmux files, and stop tmux server

**Additional Environment Variables:**
Two new environment variables are used to facilitate the tests:

- TMUX_CONFIG - Specifies the path to the configuration file. If unset, tmux will use the default configuration.
- INTEGRATION_TEST - A flag to prevent session attachment. All tests are executed outside tmux.

Please review and share your thoughts.

2025-01-31 03:13 UTC, mandos commented
@27medkamal Any plan to review it?

2025-01-31 04:32 UTC, 27medkamal commented
@mandos Apologies for the delay. Will try to review this over the next week.

2025-02-27 23:38 UTC, 27medkamal requested changes

2025-02-27 23:38 UTC, 27medkamal commented on tests/integration/lib/bats.bash
> +  export _ZO_DATA_DIR="$TEST_DIR/zoxite"
I assume `zoxite` is a typo?

2025-02-27 23:38 UTC, 27medkamal commented on bin/t
> +  if [ -n "$TMUX_CONFIG" ]; then
Can we also check `SESSION_WIZARD_INTEGRATION_TEST` here, just to be extra safe in case the user is using `TMUX_CONFIG` for anything else?

2025-02-27 23:38 UTC, 27medkamal commented on session-wizard.tmux
> +
There is a bit of duplication here in terms of defaults. Can they be unified?

2025-02-27 23:38 UTC, 27medkamal commented on session-wizard.tmux
> +
I think there is also an opportunity here to use your `set_tmux_option` across the board, not just in tests

2025-02-27 23:38 UTC, 27medkamal commented on session-wizard.tmux
> +
Thoughts?

2025-02-28 03:12 UTC, mandos commented on session-wizard.tmux
> +
`set_tmux_option` is used across the board, see main function below. Right now, I didn't want to change a lot of existing code without working tests and using `set_default_session_wizard_options` function shouldn't break users configuration.
If it will be merged it would be followed by PR with a duplication session feature and some deeper refactoring (`t` script is quite messy). 
So I would like to prepare release 1.5.0 with duplication session features, integration test fully operationals and some internal refactoring.

2025-02-28 05:01 UTC, merged

2025-02-28 05:05 UTC, 27medkamal commented
@mandos Thanks for your contribution.

Also, I'm not yet sure the duplication feature makes sense within `tmux-session-wizard`, so can't promise it will be merged in case you don't want to waste time on it.

Feel free of course to submit a refactor though.

Thanks again.

2025-02-28 05:23 UTC, mandos commented
@27medkamal Duplication feature is already implemented in my develop branch, time is already "wasted". I created it in this plugin because, at least teoretically, some core functionality can be used in both cases (creating sessions for example). But I also understand why you hesitate, it is only mildly connected with original purpose of this plugin. 

Best regards